create table avatar (id bigint generated by default as identity, file_name varchar(255), primary key (id))
create table category (id bigint generated by default as identity, created timestamp, name varchar(255), primary key (id))
create table post (id bigint generated by default as identity, created timestamp, image_url varchar(255), text varchar(255), title varchar(255), uuid varchar(255), category_id bigint, parent_id bigint, user_id bigint, primary key (id))
create table role (id bigint generated by default as identity, role varchar(255), primary key (id))
create table user (id bigint generated by default as identity, email varchar(255), enabled boolean, encrypted_password varchar(255), first_name varchar(255), last_name varchar(255), user_name varchar(255) not null, user_prefs_id bigint, primary key (id))
create table user_roles (users_id bigint not null, roles_id bigint not null)
create table user_prefs (id bigint generated by default as identity, avatar_id bigint, user_id bigint, primary key (id))
alter table avatar add constraint UK_AVATAR_FILE_NAME unique (file_name)
alter table category add constraint UK_CATEGORY_NAME unique (name)
alter table post add constraint FK_POST_CATEGORY__CATEGORY_ID foreign key (category_id) references category
alter table post add constraint FK_POST_POST__PARENT_ID foreign key (parent_id) references post
alter table post add constraint FK_POST_USER__USER_ID foreign key (user_id) references user
alter table user add constraint FK_USER_USER_PREFS__USER_PREFS_ID foreign key (user_prefs_id) references user_prefs
alter table user_roles add constraint FK_USER_ROLES_ROLE__ROLES_ID foreign key (roles_id) references role
alter table user_roles add constraint FK_USER_ROLES_USER__USERS_ID foreign key (users_id) references user
alter table user_prefs add constraint FK_USER_PREFS_AVATAR__AVATAR_ID foreign key (avatar_id) references avatar
alter table user_prefs add constraint FK_USER_PREFS_USER__USER_ID foreign key (user_id) references user